"use client";

import { useMemo, useState } from "react";

type Screen = "home" | "passport" | "login" | "dashboard" | "questions" | "documents" | "review" | "book" | "companion" | "live" | "tracking";
type ReissueForm = { application: string; applicant: string; employment: string; address: string; nonEcr: string; reasons: string[]; personalChange: string; courtCase: string; abroad: string; };
type Requirement = { id: string; title: string; detail: string; choices?: string[]; tag?: string; downloadHref?: string; downloadLabel?: string; };

const initialForm: ReissueForm = { application: "", applicant: "", employment: "", address: "", nonEcr: "", reasons: [], personalChange: "", courtCase: "", abroad: "" };
const reissueReasons = ["Exhaustion of pages", "Validity due to expire", "Validity expired", "Renewal of short validity passport", "Lost / stolen passport", "Damaged passport", "Change in personal particulars", "None of the above"];
const addressChoices = ["Aadhaar / e-Aadhaar", "Electricity bill", "Water bill", "Post-paid mobile / landline bill", "Rent agreement", "Bank passbook / statement", "Voter ID", "Spouse's passport copy"];
const dobChoices = ["Birth certificate", "Class 10 / matriculation certificate", "School leaving certificate", "PAN card", "Aadhaar / e-Aadhaar", "Service record / pension order"];

export default function UmangPassport() {
  const [screen, setScreen] = useState<Screen>("home");
  const [form, setForm] = useState<ReissueForm>(initialForm);
  const [uploads, setUploads] = useState<Record<string, boolean>>({});
  const [documentTypes, setDocumentTypes] = useState<Record<string, string>>({ address: "Aadhaar / e-Aadhaar", dob: "Birth certificate" });
  const [reviewOpen, setReviewOpen] = useState(false);
  const [resolved, setResolved] = useState(false);
  const [booked, setBooked] = useState(false);
  const [applicationStarted, setApplicationStarted] = useState(false);
  const go = (next: Screen) => { setScreen(next); window.scrollTo(0, 0); };
  const requirements = useMemo(() => buildRequirements(form), [form]);

  return <main className="umang-canvas"><section className="umang-phone"><PhoneStatus /><TopBar screen={screen} back={() => go(backScreen(screen))} />
    <div className="umang-scroll">
      {screen === "home" && <UmangHome go={go} />}
      {screen === "passport" && <PassportSeva go={go} />}
      {screen === "login" && <Login go={go} />}
      {screen === "dashboard" && <Dashboard go={go} applicationStarted={applicationStarted} startApplication={()=>setApplicationStarted(true)} />}
      {screen === "questions" && <Questions form={form} setForm={setForm} go={go} />}
      {screen === "documents" && <Documents requirements={requirements} uploads={uploads} setUploads={setUploads} documentTypes={documentTypes} setDocumentTypes={setDocumentTypes} go={go} />}
      {screen === "review" && <Review requirements={requirements} documentTypes={documentTypes} open={reviewOpen} setOpen={setReviewOpen} resolved={resolved} setResolved={setResolved} go={go} />}
      {screen === "book" && <Booking booked={booked} setBooked={setBooked} go={go} />}
      {screen === "companion" && <Companion go={go} />}
      {screen === "live" && <LiveVisit go={go} />}
      {screen === "tracking" && <Tracking go={go} />}
    </div><Powered />{screen === "home" && <BottomNav />}
  </section></main>;
}

function backScreen(screen: Screen): Screen { if (screen === "passport") return "home"; if (screen === "login") return "passport"; if (screen === "dashboard") return "passport"; if (screen === "questions") return "dashboard"; if (screen === "documents") return "questions"; if (screen === "review") return "documents"; if (screen === "book") return "review"; if (screen === "companion") return "book"; if (screen === "live") return "companion"; if (screen === "tracking") return "dashboard"; return "home"; }
function PhoneStatus(){return <div className="phone-status"><b>9:41</b><span>●●●　◒　▰</span></div>}
function TopBar({screen,back}:{screen:Screen;back:()=>void}) { const simple=screen === "home"; const title=screen === "passport" ? "Passport Seva" : screen === "dashboard" ? "Passport services" : screen === "questions" ? "Reissue passport" : screen === "documents" ? "Required documents" : screen === "review" ? "Document review" : screen === "book" ? "Appointment" : screen === "companion" || screen === "live" ? "My appointment" : screen === "tracking" ? "Track application" : "Passport Seva"; return <header className={simple?"umang-top home-top":"umang-top"}>{simple?<><div className="umang-ident"><span>♜</span><b>UMANG</b></div><div className="top-icons">◉　◎　♟</div></>:<><button onClick={back} className="back" aria-label="Back">‹</button><h1>{title}</h1><button className="more" aria-label="More options">⋮</button></>}</header>}
function BottomNav(){return <nav className="umang-nav"><button className="active">⌂<span>myUmang</span></button><button>⠿<span>Services</span></button><button>▣<span>DigiLocker</span></button><button>▤<span>Schemes</span></button><button>◉<span>Profile</span></button></nav>}
function Powered(){return <div className="powered">Powered by <b>Passport Seva</b></div>}

function UmangHome({go}:{go:(p:Screen)=>void}){return <section className="home-screen"><div className="umang-search">Search for <b>“Aadhaar Services”</b><span>⌕　🎙</span></div><button className="online-banner" onClick={()=>go("passport")}><div><small>NEW ON UMANG</small><h2>Passport services are<br/><em>completely online.</em></h2><p>Renew, prepare, visit and track your passport in one journey.</p><b>Explore Passport Seva　→</b></div><span className="banner-passport">♜</span></button><div className="dots"><i className="selected"/><i/><i/><i/></div><button className="digipin"><span>✓</span><b>Know your DIGIPIN</b><em>→</em></button><h2 className="quick-title">⌁ Quick Services</h2><div className="quick-grid"><Quick icon="♢" name="TOTP\nAuthenticator" color="orange"/><Quick icon="♥" name="Health" color="green"/><Quick icon="☀" name="Emergency" color="red"/><Quick icon="✈" name="Travel" color="purple"/></div></section>}
function Quick({icon,name,color}:{icon:string;name:string;color:string}){return <button className="quick"><span className={color}>{icon}</span><b>{name.split("\n").map((x,i)=><span key={`${x}-${i}`}>{x}<br/></span>)}</b></button>}

function PassportSeva({go}:{go:(p:Screen)=>void}){return <section className="passport-service"><div className="service-hero"><div className="language">English⌄</div><div className="ps-brand"><span>♜</span><div><b>Passport Seva</b><small>Government of India</small></div></div></div><div className="service-body"><div className="service-search">Search services here...</div><button className="sign-banner" onClick={()=>go("login")}><span>▣</span><div><b>Sign in to Passport Seva with DigiLocker</b><p>Use your verified details to manage your passport online.</p></div><i>›</i></button><h2>General Services</h2><GeneralServices /></div></section>}
function GeneralServices(){return <><ServiceRow icon="▤" name="Locate Centre" color="blue"/><ServiceRow icon="▧" name="Fee Calculator" color="gold"/><ServiceRow icon="▤" name="Status Tracker" color="green"/><ServiceRow icon="▦" name="Check Appointment Availability" color="pink"/><ServiceRow icon="♙" name="Document Advisor" color="purple"/></>}
function ServiceRow({icon,name,color}:{icon:string;name:string;color:string}){return <button className="service-row"><span className={color}>{icon}</span><b>{name}</b><i>ⓘ</i></button>}

function Login({go}:{go:(p:Screen)=>void}){return <section className="login-screen"><div className="login-lock">▣</div><h2>Continue to Passport Seva</h2><p>Access your passport services securely through UMANG.</p><button className="login-option primary-login" onClick={()=>go("dashboard")}><span>▣</span><div><b>Sign in with DigiLocker</b><small>Use verified identity and document records</small></div><i>›</i></button><div className="login-or"><span/>OR<span/></div><button className="login-option" onClick={()=>go("dashboard")}><span>✉</span><div><b>Sign in with email</b><small>Your account will be synced with DigiLocker</small></div><i>›</i></button></section>}

function Dashboard({go,applicationStarted,startApplication}:{go:(p:Screen)=>void;applicationStarted:boolean;startApplication:()=>void}){return <section className="dashboard"><p className="eyebrow">PASSPORT SEVA ON UMANG</p><h2>Good afternoon, Anushka</h2><article className="passport-card"><div className="passport-card-top"><span>REPUBLIC OF INDIA</span><b>पासपोर्ट　PASSPORT</b><i>✦</i></div><div className="passport-card-main"><div className="card-photo">AJ</div><div><small>PASSPORT NUMBER</small><b>N1234567</b><small>NAME</small><b>ANUSHKA JAIN</b><small>EXPIRY</small><b>14 MAY 2032</b></div></div><em>▣ Powered by DigiLocker</em></article><button className="record-cta"><span>▤</span><div><b>View passport record</b><small>Details, validity and issued documents</small></div><i>›</i></button><h3>Passport services</h3><div className="passport-actions"><button onClick={()=>{startApplication();go("questions")}}><span>↻</span><b>Reissue passport</b><small>Renew, update or replace</small></button><button className="coming"><span>◌</span><b>Apply for visa</b><small>Coming soon</small></button></div>{applicationStarted&&<button className="ongoing-application" onClick={()=>go("questions")}><span className="ongoing-icon">↻</span><div><small>ONGOING APPLICATION</small><b>Passport reissue</b><p>Draft saved · Complete your assessment</p></div><i>Resume　›</i></button>}<h3>General services</h3><GeneralServices /></section>}

function Questions({form,setForm,go}:{form:ReissueForm;setForm:(value:ReissueForm)=>void;go:(p:Screen)=>void}) {
  const set = (key: Exclude<keyof ReissueForm,"reasons">, value: string) => setForm({...form,[key]:value});
  const toggleReason = (value:string) => { const reasons = form.reasons.includes(value) ? form.reasons.filter(item=>item!==value) : [...form.reasons.filter(item=>item!=="None of the above"),value]; setForm({...form,reasons:value === "None of the above" ? [value] : reasons}); };
  const valid = Boolean(form.application && form.applicant && form.employment && form.address && form.nonEcr && form.reasons.length && form.courtCase && form.abroad && (!form.reasons.includes("Change in personal particulars") || form.personalChange));
  return <section className="flow-screen assessment-screen"><p className="step-label">REISSUE ASSESSMENT</p><h2>Tell us about your passport</h2><p>Answer the questions below and we&apos;ll generate a personalised document pack before you book.</p>
    <OptionQuestion title="Application type" required values={["Normal", "Tatkaal"]} chosen={form.application} choose={(v)=>set("application",v)} />
    <OptionQuestion title="Applicant category" required values={["Adult", "Minor"]} chosen={form.applicant} choose={(v)=>set("applicant",v)} />
    <OptionQuestion title="Employment type" required values={["Government / PSU / statutory body", "Retired government official", "Private / self-employed / other"]} chosen={form.employment} choose={(v)=>set("employment",v)} />
    <OptionQuestion title="Is your present address different from the existing passport?" required values={["Yes, it has changed", "No, it is the same"]} chosen={form.address} choose={(v)=>set("address",v)} />
    <OptionQuestion title="Are you eligible for Non-ECR?" required values={["Yes", "No", "I’m not sure"]} chosen={form.nonEcr} choose={(v)=>set("nonEcr",v)} />
    <MultiQuestion title="Why do you need a reissue? Select every applicable reason." required values={reissueReasons} chosen={form.reasons} toggle={toggleReason}/>
    {form.reasons.includes("Change in personal particulars") && <OptionQuestion title="Which detail needs to change?" required values={["Name / surname", "Date or place of birth", "Spouse name", "Gender", "Appearance / signature", "Other personal detail"]} chosen={form.personalChange} choose={(v)=>set("personalChange",v)} />}
    <OptionQuestion title="Do you have an ongoing court case or a court restriction relating to travel?" required values={["No", "Yes"]} chosen={form.courtCase} choose={(v)=>set("courtCase",v)} />
    <OptionQuestion title="Was the passport lost or damaged outside India?" required values={["No", "Yes"]} chosen={form.abroad} choose={(v)=>set("abroad",v)} />
    <p className="form-note">This is a prototype pre-check. Passport Seva may ask for additional documents after review.</p>
    <button className="flow-cta" disabled={!valid} onClick={()=>go("documents")}>Generate my document list　→</button>
  </section>
}
function OptionQuestion({title,values,chosen,choose,required}:{title:string;values:string[];chosen:string;choose:(x:string)=>void;required?:boolean}){return <div className="question"><b>{title}{required&&<em>*</em>}</b><div>{values.map(x=><button type="button" onClick={()=>choose(x)} className={chosen===x?"chosen":""} key={x}><i>{chosen===x?"●":"○"}</i>{x}</button>)}</div></div>}
function MultiQuestion({title,values,chosen,toggle,required}:{title:string;values:string[];chosen:string[];toggle:(x:string)=>void;required?:boolean}){return <div className="question multi-question"><b>{title}{required&&<em>*</em>}</b><div>{values.map(x=><button type="button" onClick={()=>toggle(x)} className={chosen.includes(x)?"chosen":""} key={x}><i>{chosen.includes(x)?"✓":"□"}</i>{x}</button>)}</div></div>}

function buildRequirements(form: ReissueForm): Requirement[] {
  const hasLoss = form.reasons.some(value => value === "Lost / stolen passport" || value === "Damaged passport");
  const hasChange = form.reasons.includes("Change in personal particulars");
  const needsAddress = form.address === "Yes, it has changed" || hasLoss || hasChange;
  const items: Requirement[] = [
    {id:"passport",title:"Existing passport and copies",detail:"Bring the original existing passport to the PSK. Attach clearly readable, self-attested copies of the first two and last two pages, ECR / Non-ECR page, observation page and any validity-extension page.",tag:"Mandatory"},
    {id:"address",title:"Proof of present address",detail:needsAddress ? "Attach one accepted document that shows the current address entered in this application." : "Attach one accepted proof of your present address, even if it matches the existing passport.",choices:addressChoices,tag:"Mandatory"},
    {id:"dob",title:"Proof of date of birth",detail:"Attach one accepted proof that supports the date of birth in the application.",choices:dobChoices,tag:"Mandatory"},
  ];
  if (hasLoss) items.push({id:"affidavit",title:"Affidavit for lost / damaged passport",detail:"Complete the declaration describing how and where the passport was lost or damaged, then attach the signed Annexure F.",tag:"Mandatory",downloadHref:"https://passportindia.gov.in/AppOnlineProject/pdf/Revised_Annexures.pdf",downloadLabel:"Download Annexure F · official template"});
  if (form.reasons.includes("Lost / stolen passport")) items.push({id:"fir",title:"FIR / police report",detail:"Attach the FIR or police report for the lost or stolen passport. If the passport was lost abroad, attach the Emergency Certificate if issued.",tag:"Mandatory"});
  if (hasChange) { const changeDetail = form.personalChange === "Name / surname" ? "Attach the supporting record for the name change, plus two public or school documents in the changed name where applicable." : form.personalChange === "Date or place of birth" ? "Attach the supporting birth record and the required declaration explaining the correction." : "Attach the official record that supports the requested change in personal particulars."; items.push({id:"change",title:"Proof for the requested change",detail:changeDetail,tag:"Mandatory"}); }
  if (form.applicant === "Minor") items.push({id:"minor",title:"Parent / guardian declaration",detail:"Attach the applicable parent or guardian declaration and supporting documents for the minor applicant.",tag:"Mandatory"});
  if (form.employment === "Government / PSU / statutory body") items.push({id:"noc",title:"Employer clearance",detail:"Attach the applicable No Objection Certificate or Prior Intimation letter from your employer.",tag:"Required for your employment type"});
  if (form.courtCase === "Yes") items.push({id:"court",title:"Court order and undertaking",detail:"Attach the relevant court order(s) and undertaking that cover the pending case and travel permission.",tag:"Mandatory"});
  return items;
}

function Documents({requirements,uploads,setUploads,documentTypes,setDocumentTypes,go}:{requirements:Requirement[];uploads:Record<string,boolean>;setUploads:(v:Record<string,boolean>)=>void;documentTypes:Record<string,string>;setDocumentTypes:(v:Record<string,string>)=>void;go:(p:Screen)=>void}) { const complete = requirements.every(requirement=>uploads[requirement.id]); return <section className="flow-screen documents-screen"><p className="step-label">YOUR PERSONALISED DOCUMENT LIST</p><h2>Attach your documents</h2><p>Upload each item before requesting a review. You will still carry the originals to your appointment.</p><div className="requirements-list">{requirements.map(requirement=><RequirementCard key={requirement.id} requirement={requirement} attached={Boolean(uploads[requirement.id])} selectedType={documentTypes[requirement.id] || requirement.choices?.[0] || ""} setType={(value)=>setDocumentTypes({...documentTypes,[requirement.id]:value})} toggle={()=>setUploads({...uploads,[requirement.id]:!uploads[requirement.id]})}/>)}</div><p className="form-note">A DigiLocker record can help pre-fill details; it does not replace originals required at the Passport Seva Kendra.</p>{complete&&<button className="flow-cta" onClick={()=>go("review")}>Submit for document review　→</button>}</section>}
function RequirementCard({requirement,attached,selectedType,setType,toggle}:{requirement:Requirement;attached:boolean;selectedType:string;setType:(value:string)=>void;toggle:()=>void}) {return <article className="requirement"><div className="requirement-head"><span className={attached?"done":"pending"}>{attached?"✓":"!"}</span><div><b>{requirement.title}</b><em>{requirement.tag}</em></div></div><p>{requirement.detail}</p>{requirement.choices&&<label>Document you&apos;re attaching<select value={selectedType} onChange={event=>setType(event.target.value)}>{requirement.choices.map(choice=><option key={choice}>{choice}</option>)}</select></label>}{requirement.downloadHref&&<a className="annexure-download" href={requirement.downloadHref} target="_blank" rel="noreferrer"><span>⇩</span><div><b>{requirement.downloadLabel}</b><small>Passport Seva document · PDF</small></div><i>›</i></a>}<div className="attachment-row"><span>{attached ? `${fileName(requirement.id, selectedType)} attached` : "No document attached"}</span><button type="button" onClick={toggle}>{attached ? "Change" : "Attach document"}</button></div></article>}
function fileName(id:string,type:string){const normalized=(type || id).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");return `${normalized || id}.pdf`}

function Review({requirements,documentTypes,open,setOpen,resolved,setResolved,go}:{requirements:Requirement[];documentTypes:Record<string,string>;open:boolean;setOpen:(v:boolean)=>void;resolved:boolean;setResolved:(v:boolean)=>void;go:(p:Screen)=>void}){ const hasAffidavit = requirements.some(item=>item.id === "affidavit"); return <section className="flow-screen review-screen"><p className="step-label">PASSPORT SEVA DOCUMENT REVIEW</p><h2>{resolved ? "Ready to book" : "A few items need attention"}</h2><p>{resolved ? "The document pack is complete for appointment booking." : "The pre-check caught these issues before your visit."}</p><div className="review-list"><ReviewRow title="Existing passport and copies" text="Accepted — all required pages are readable" success/><ReviewRow title={`Proof of present address${documentTypes.address ? ` · ${documentTypes.address}` : ""}`} text={resolved ? "Accepted — address and name match your application" : "Needs attention — the supporting evidence is incomplete"} success={resolved} missing={!resolved} onClick={()=>setOpen(!open)}/><ReviewRow title="Proof of date of birth" text="Accepted — details match the application" success/>{hasAffidavit&&<ReviewRow title="Lost / damaged passport affidavit" text="Accepted — Annexure F has been attached" success/>}{requirements.filter(item=>!["passport","address","dob","affidavit"].includes(item.id)).map(item=><ReviewRow key={item.id} title={item.title} text="Accepted — document is readable" success/>)}</div>{open&&!resolved&&<div className="missing-box"><b>Present-address proof needs more information</b><p>The uploaded rent agreement does not include the signatures of two Indian-citizen witnesses or supporting identity records. The property owner&apos;s identity proof is also required.</p><ul><li>Two witness signatures on the agreement</li><li>Self-attested ID proof of both witnesses</li><li>Self-attested ID proof of the property owner</li></ul><button onClick={()=>setResolved(true)}>Re-upload supporting documents</button></div>}{!resolved&&<div className="additional-docs"><b>Additional documents requested</b><span>Witness ID proof × 2</span><span>Owner ID proof</span></div>}<p className="review-disclaimer">Mock pre-check outcome for this prototype. A Passport Seva officer makes the final decision and may request more records.</p>{resolved&&<button className="flow-cta" onClick={()=>go("book")}>Schedule appointment　→</button>}</section>}
function ReviewRow({title,text,success,missing,onClick}:{title:string;text:string;success?:boolean;missing?:boolean;onClick?:()=>void}){return <button type="button" onClick={onClick} className="review-row"><span className={success?"success":"attention"}>{success?"✓":"!"}</span><div><b>{title}</b><small>{text}</small></div>{missing&&<i>View details　⌄</i>}</button>}

function Booking({booked,setBooked,go}:{booked:boolean;setBooked:(v:boolean)=>void;go:(p:Screen)=>void}){if(booked)return <section className="confirmation"><div className="confirmed">✓</div><h2>Appointment booked</h2><p>Your appointment and updates are available in UMANG.</p><div className="token"><small>TOKEN NUMBER</small><b>BNC-048</b><span>Passport Seva Kendra, Bengaluru</span><hr/><b>10:40 AM</b><span>Report by 10:15 AM · 03 Sep 2026</span></div><button className="flow-cta" onClick={()=>go("companion")}>Open appointment companion　→</button></section>; return <section className="flow-screen"><p className="step-label">APPOINTMENT</p><h2>Choose your appointment</h2><p>Your document pack is ready for an appointment. Carry the originals for final matching and biometrics.</p><div className="centre-card"><span>●</span><div><small>PASSPORT SEVA KENDRA</small><b>Bengaluru, Karnataka</b></div><button>Change</button></div><div className="slot-list">{["Tomorrow · 10:40 AM","Tomorrow · 12:20 PM","Friday · 09:15 AM"].map((x,i)=><button onClick={()=>setBooked(true)} key={x}><b>{x}</b><span>{i===0?"Recommended":"Available"}　›</span></button>)}</div></section>}

function Companion({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label">YOUR APPOINTMENT</p><h2>We&apos;ll help you arrive prepared</h2><div className="arrival-card"><b>Report by 10:15 AM</b><p>Passport Seva Kendra, Bengaluru<br/>Token BNC-048 · Appointment 10:40 AM</p></div><h3>Bring these originals</h3><ul className="bring-list"><li>Existing passport + self-attested copies</li><li>Original proof of present address</li><li>Original proof of date of birth</li><li>All change / affidavit supporting records</li></ul><div className="facilities"><b>At the centre</b><span>♿ Accessible entrance　☕ Refreshments　⌖ Parking nearby</span></div><button className="flow-cta" onClick={()=>go("live")}>I&apos;ve arrived at the centre　→</button><button className="text-action">Reschedule / cancel appointment</button></section>}
function LiveVisit({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label live-label">● APPOINTMENT IN PROGRESS</p><h2>Report directly to Counter C</h2><p>Your earlier completed steps are preserved. You don&apos;t need to restart at Counter A.</p><div className="queue-status"><span>●</span><div><small>LIVE QUEUE</small><b>You&apos;re next in 12 minutes</b></div></div><div className="timeline"><Time done title="Token verified" text="10:17 AM"/><Time done title="Document pre-check complete" text="Resumed from earlier visit"/><Time active title="Counter C · Biometrics" text="Proceed when called"/><Time title="Granting decision" text="After biometrics"/></div><button className="flow-cta" onClick={()=>go("tracking")}>Complete submission demo　→</button></section>}
function Time({title,text,done,active}:{title:string;text:string;done?:boolean;active?:boolean}){return <div className="time"><span className={done?"done":active?"active":""}>{done?"✓":active?"3":"4"}</span><div><b>{title}</b><small>{text}</small></div></div>}
function Tracking({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label">PASSPORT TRACKING</p><h2>Your passport is moving forward</h2><p>UMANG will keep you informed at every important moment.</p><div className="tracking-id"><small>APPLICATION NUMBER</small><b>BN1064822518426</b><span>Submitted</span></div><div className="timeline"><Time done title="Application submitted" text="All PSK checks complete"/><Time active title="Police verification" text="Officer assigned · expected within 5 days"/><Time title="Passport printing" text="After verification clears"/><Time title="Dispatch" text="Delivery tracking will appear here"/></div><div className="officer"><span>♙</span><div><small>POLICE VERIFICATION</small><b>Officer Rajesh Kumar</b><p>Indiranagar Police Station · Your physical verification appointment will appear here.</p></div></div><button className="flow-cta" onClick={()=>go("home")}>Back to myUmang　→</button></section>}
