"use client";

import { useState } from "react";

type Screen = "home" | "passport" | "login" | "dashboard" | "questions" | "documents" | "review" | "book" | "companion" | "live" | "tracking";

export default function UmangPassport() {
  const [screen, setScreen] = useState<Screen>("home");
  const [reason, setReason] = useState("");
  const [address, setAddress] = useState("");
  const [uploaded, setUploaded] = useState(false);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [resolved, setResolved] = useState(false);
  const [booked, setBooked] = useState(false);
  const go = (next: Screen) => { setScreen(next); window.scrollTo(0, 0); };

  return <main className="umang-canvas"><section className="umang-phone"><PhoneStatus /><TopBar screen={screen} back={() => go(screen === "passport" ? "home" : "dashboard")} />
    <div className="umang-scroll">
      {screen === "home" && <UmangHome go={go} />}
      {screen === "passport" && <PassportSeva go={go} />}
      {screen === "login" && <Login go={go} />}
      {screen === "dashboard" && <Dashboard go={go} />}
      {screen === "questions" && <Questions reason={reason} address={address} setReason={setReason} setAddress={setAddress} go={go} />}
      {screen === "documents" && <Documents uploaded={uploaded} setUploaded={setUploaded} go={go} />}
      {screen === "review" && <Review open={reviewOpen} setOpen={setReviewOpen} resolved={resolved} setResolved={setResolved} go={go} />}
      {screen === "book" && <Booking booked={booked} setBooked={setBooked} go={go} />}
      {screen === "companion" && <Companion go={go} />}
      {screen === "live" && <LiveVisit go={go} />}
      {screen === "tracking" && <Tracking go={go} />}
    </div>
    <Powered />
    {screen === "home" && <BottomNav />}
  </section></main>;
}

function PhoneStatus(){return <div className="phone-status"><b>9:41</b><span>●●●　◒　▰</span></div>}
function TopBar({screen,back}:{screen:Screen;back:()=>void}) { const simple=screen === "home"; const title=screen === "passport" ? "Passport Seva" : screen === "dashboard" ? "Passport services" : screen === "questions" ? "Reissue passport" : screen === "documents" || screen === "review" ? "Document check" : screen === "book" ? "Appointment" : screen === "companion" || screen === "live" ? "My appointment" : screen === "tracking" ? "Track application" : "Passport Seva"; return <header className={simple?"umang-top home-top":"umang-top"}>{simple?<><div className="umang-ident"><span>♜</span><b>UMANG</b></div><div className="top-icons">◉　◎　♟</div></>:<><button onClick={back} className="back">‹</button><h1>{title}</h1><button className="more">⋮</button></>}</header>}
function BottomNav(){return <nav className="umang-nav"><button className="active">⌂<span>myUmang</span></button><button>⠿<span>Services</span></button><button>▣<span>DigiLocker</span></button><button>▤<span>Schemes</span></button><button>◉<span>Profile</span></button></nav>}
function Powered(){return <div className="powered">Powered by <b>Passport Seva</b></div>}

function UmangHome({go}:{go:(p:Screen)=>void}){return <section className="home-screen"><div className="umang-search">Search for <b>“Aadhaar Services”</b><span>⌕　🎙</span></div><button className="online-banner" onClick={()=>go("passport")}><div><small>NEW ON UMANG</small><h2>Passport services are<br/><em>completely online.</em></h2><p>Renew, prepare, visit and track your passport in one journey.</p><b>Explore Passport Seva　→</b></div><span className="banner-passport">♜</span></button><div className="dots"><i className="selected"/><i/><i/><i/></div><button className="digipin"><span>✓</span><b>Know your DIGIPIN</b><em>→</em></button><h2 className="quick-title">⌁ Quick Services</h2><div className="quick-grid"><Quick icon="♢" name="TOTP\nAuthenticator" color="orange"/><Quick icon="♥" name="Health" color="green"/><Quick icon="☀" name="Emergency" color="red"/><Quick icon="✈" name="Travel" color="purple"/></div></section>}
function Quick({icon,name,color}:{icon:string;name:string;color:string}){return <button className="quick"><span className={color}>{icon}</span><b>{name.split("\n").map(x=><>{x}<br/></>)}</b></button>}

function PassportSeva({go}:{go:(p:Screen)=>void}){return <section className="passport-service"><div className="service-hero"><div className="language">English⌄</div><div className="ps-brand"><span>♜</span><div><b>Passport Seva</b><small>Government of India</small></div></div></div><div className="service-body"><div className="service-search">Search services here...</div><button className="sign-banner" onClick={()=>go("login")}><span>▣</span><div><b>Sign in to Passport Seva with DigiLocker</b><p>Use your verified details to manage your passport online.</p></div><i>›</i></button><h2>General Services</h2><ServiceRow icon="▤" name="Locate Centre" color="blue"/><ServiceRow icon="▧" name="Fee Calculator" color="gold"/><ServiceRow icon="▤" name="Status Tracker" color="green"/><ServiceRow icon="▦" name="Check Appointment Availability" color="pink"/><ServiceRow icon="♙" name="Document Advisor" color="purple"/></div></section>}
function ServiceRow({icon,name,color}:{icon:string;name:string;color:string}){return <button className="service-row"><span className={color}>{icon}</span><b>{name}</b><i>ⓘ</i></button>}

function Login({go}:{go:(p:Screen)=>void}){return <section className="login-screen"><div className="login-lock">▣</div><h2>Continue to Passport Seva</h2><p>Access your passport services securely through UMANG.</p><button className="login-option primary-login" onClick={()=>go("dashboard")}><span>▣</span><div><b>Sign in with DigiLocker</b><small>Use verified identity and document records</small></div><i>›</i></button><div className="login-or"><span/>OR<span/></div><button className="login-option"><span>✉</span><div><b>Sign in with email</b><small>Your account will be synced with DigiLocker</small></div><i>›</i></button></section>}

function Dashboard({go}:{go:(p:Screen)=>void}){return <section className="dashboard"><p className="eyebrow">PASSPORT SEVA ON UMANG</p><h2>Good afternoon, Anushka</h2><article className="passport-card"><div className="passport-card-top"><span>REPUBLIC OF INDIA</span><b>पासपोर्ट　PASSPORT</b><i>✦</i></div><div className="passport-card-main"><div className="card-photo">AJ</div><div><small>PASSPORT NUMBER</small><b>N1234567</b><small>NAME</small><b>ANUSHKA JAIN</b><small>EXPIRY</small><b>14 MAY 2032</b></div></div><em>▣ Powered by DigiLocker</em></article><button className="record-cta"><span>▤</span><div><b>View passport record</b><small>Details, validity and issued documents</small></div><i>›</i></button><h3>Passport services</h3><div className="passport-actions"><button onClick={()=>go("questions")}><span>↻</span><b>Reissue passport</b><small>Renew, update or replace</small></button><button className="coming"><span>◌</span><b>Apply for visa</b><small>Coming soon</small></button><button><span>▦</span><b>Track application</b><small>Follow every step</small></button></div><h3>General services</h3><ServiceRow icon="▤" name="Locate Centre" color="blue"/><ServiceRow icon="▧" name="Fee Calculator" color="gold"/></section>}

function Questions({reason,address,setReason,setAddress,go}:{reason:string;address:string;setReason:(s:string)=>void;setAddress:(s:string)=>void;go:(p:Screen)=>void}){const okay=Boolean(reason&&address); return <section className="flow-screen"><p className="step-label">STEP 1 OF 4</p><h2>Tell us what changed</h2><p>We&apos;ll prepare the documents you need before you book an appointment.</p><Question title="Why do you need a reissue?" values={["Damaged passport","Expired passport","Lost passport","Change in details"]} chosen={reason} choose={setReason}/><Question title="Is your current address different from your existing passport?" values={["Different address","Same address"]} chosen={address} choose={setAddress}/><button className="flow-cta" disabled={!okay} onClick={()=>go("documents")}>Continue　→</button></section>}
function Question({title,values,chosen,choose}:{title:string;values:string[];chosen:string;choose:(x:string)=>void}){return <div className="question"><b>{title}</b><div>{values.map(x=><button onClick={()=>choose(x)} className={chosen===x?"chosen":""} key={x}><i>{chosen===x?"●":"○"}</i>{x}</button>)}</div></div>}

function Documents({uploaded,setUploaded,go}:{uploaded:boolean;setUploaded:(v:boolean)=>void;go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label">STEP 2 OF 4</p><h2>Prepare your documents</h2><p>Documents already issued by the government have been securely fetched.</p><div className="document-list"><Document title="Aadhaar card" sub="Identity and current address" tag="Fetched via DigiLocker" state="done"/><Document title="Old passport" sub="Passport record" tag="Fetched via DigiLocker" state="done"/><Document title="Rental agreement" sub={uploaded?"rental-agreement.pdf attached":"Document required to upload"} state={uploaded?"done":"upload"} action={()=>setUploaded(!uploaded)} actionText={uploaded?"Change":"Upload"}/></div>{uploaded&&<button className="flow-cta" onClick={()=>go("review")}>Review documents　→</button>}</section>}
function Document({title,sub,tag,state,action,actionText}:{title:string;sub:string;tag?:string;state:string;action?:()=>void;actionText?:string}){return <div className="document"><span className={state}>{state==="done"?"✓":"↑"}</span><div><b>{title}</b><small>{sub}</small>{tag&&<em>{tag}</em>}</div>{action&&<button onClick={action}>{actionText}</button>}</div>}

function Review({open,setOpen,resolved,setResolved,go}:{open:boolean;setOpen:(v:boolean)=>void;resolved:boolean;setResolved:(v:boolean)=>void;go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label">DOCUMENT REVIEW</p><h2>{resolved?"Documents ready":"A few details need attention"}</h2><p>{resolved?"Everything is ready for a confident appointment.":"We found an issue before you had to travel."}</p><div className="review-list"><ReviewRow title="Aadhaar card" text="All information is present" success/><ReviewRow title="Old passport" text="All information is present" success/><ReviewRow title="Rental agreement" text={resolved?"Information complete":"Missing information"} missing={!resolved} onClick={()=>setOpen(!open)}/>{open&&!resolved&&<div className="missing-box"><b>Witness signatures are missing</b><p>Your rental agreement must include signatures from two Indian-citizen witnesses. Add their self-attested ID proofs and the property owner&apos;s self-attested ID proof.</p><ul><li>Signatures from two witnesses</li><li>Identity proof of both witnesses</li><li>Identity proof of property owner</li></ul><button onClick={()=>setResolved(true)}>Re-upload supporting documents</button></div>}</div>{resolved&&<button className="flow-cta" onClick={()=>go("book")}>Schedule appointment　→</button>}</section>}
function ReviewRow({title,text,success,missing,onClick}:{title:string;text:string;success?:boolean;missing?:boolean;onClick?:()=>void}){return <button onClick={onClick} className="review-row"><span className={success?"success":"attention"}>{success?"✓":"!"}</span><div><b>{title}</b><small>{text}</small></div>{missing&&<i>View details　⌄</i>}</button>}

function Booking({booked,setBooked,go}:{booked:boolean;setBooked:(v:boolean)=>void;go:(p:Screen)=>void}){if(booked)return <section className="confirmation"><div className="confirmed">✓</div><h2>Appointment booked</h2><p>Your appointment and updates are available in UMANG.</p><div className="token"><small>TOKEN NUMBER</small><b>BNC-048</b><span>Passport Seva Kendra, Bengaluru</span><hr/><b>10:40 AM</b><span>Report by 10:15 AM · 03 Sep 2026</span></div><button className="flow-cta" onClick={()=>go("companion")}>Open appointment companion　→</button></section>; return <section className="flow-screen"><p className="step-label">STEP 3 OF 4</p><h2>Choose your appointment</h2><p>Your documents are pre-verified. Bring originals for final matching and biometrics.</p><div className="centre-card"><span>●</span><div><small>PASSPORT SEVA KENDRA</small><b>Bengaluru, Karnataka</b></div><button>Change</button></div><div className="slot-list">{["Tomorrow · 10:40 AM","Tomorrow · 12:20 PM","Friday · 09:15 AM"].map((x,i)=><button onClick={()=>setBooked(true)} key={x}><b>{x}</b><span>{i===0?"Recommended":"Available"}　›</span></button>)}</div></section>}

function Companion({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label">YOUR APPOINTMENT</p><h2>We&apos;ll help you arrive prepared</h2><div className="arrival-card"><b>Report by 10:15 AM</b><p>Passport Seva Kendra, Bengaluru<br/>Token BNC-048 · Appointment 10:40 AM</p></div><h3>Bring these originals</h3><ul className="bring-list"><li>Old passport + self-attested copies</li><li>Aadhaar card</li><li>Signed rental agreement + supporting IDs</li></ul><div className="facilities"><b>At the centre</b><span>♿ Accessible entrance　☕ Refreshments　⌖ Parking nearby</span></div><button className="flow-cta" onClick={()=>go("live")}>I&apos;ve arrived at the centre　→</button><button className="text-action">Reschedule / cancel appointment</button></section>}
function LiveVisit({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label live-label">● APPOINTMENT IN PROGRESS</p><h2>Report directly to Counter C</h2><p>Your earlier completed steps are preserved. You don&apos;t need to restart at Counter A.</p><div className="queue-status"><span>●</span><div><small>LIVE QUEUE</small><b>You&apos;re next in 12 minutes</b></div></div><div className="timeline"><Time done title="Token verified" text="10:17 AM"/><Time done title="Document pre-check complete" text="Resumed from earlier visit"/><Time active title="Counter C · Biometrics" text="Proceed when called"/><Time title="Granting decision" text="After biometrics"/></div><button className="flow-cta" onClick={()=>go("tracking")}>Complete submission demo　→</button></section>}
function Time({title,text,done,active}:{title:string;text:string;done?:boolean;active?:boolean}){return <div className="time"><span className={done?"done":active?"active":""}>{done?"✓":active?"3":"4"}</span><div><b>{title}</b><small>{text}</small></div></div>}
function Tracking({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label">PASSPORT TRACKING</p><h2>Your passport is moving forward</h2><p>UMANG will keep you informed at every important moment.</p><div className="tracking-id"><small>APPLICATION NUMBER</small><b>BN1064822518426</b><span>Submitted</span></div><div className="timeline"><Time done title="Application submitted" text="All PSK checks complete"/><Time active title="Police verification" text="Officer assigned · expected within 5 days"/><Time title="Passport printing" text="After verification clears"/><Time title="Dispatch" text="Delivery tracking will appear here"/></div><div className="officer"><span>♙</span><div><small>POLICE VERIFICATION</small><b>Officer Rajesh Kumar</b><p>Indiranagar Police Station · Your physical verification appointment will appear here.</p></div></div><button className="flow-cta" onClick={()=>go("home")}>Back to myUmang　→</button></section>}
