"use client";

import { useEffect, useMemo, useState } from "react";

type Screen = "home" | "passport" | "login" | "dashboard" | "questions" | "documents" | "review" | "book" | "companion" | "live" | "tracking";
type ReissueForm = { application: string; applicant: string; employment: string; address: string; nonEcr: string; reasons: string[]; personalChange: string; courtCase: string; abroad: string; damageLevel: string; policeReport: string; };
type Requirement = { id: string; title: string; detail: string; choices?: string[]; tag?: string; downloadHref?: string; downloadLabel?: string; };
type PassportCenter = { id: string; city: string; rpo: string; name: string; kind: "PSK" | "POPSK"; area: string; slots: { id: string; label: string; availability: string; }[]; };
type VisitState = "scheduled" | "checkedIn" | "documentsPending" | "rescheduled";

const initialForm: ReissueForm = { application: "", applicant: "", employment: "", address: "", nonEcr: "", reasons: [], personalChange: "", courtCase: "", abroad: "", damageLevel: "", policeReport: "" };
const reissueReasons = ["Exhaustion of pages", "Validity due to expire", "Validity expired", "Renewal of short validity passport", "Lost / stolen passport", "Damaged passport", "Change in personal particulars", "None of the above"];
const addressChoices = ["Aadhaar / e-Aadhaar", "Electricity bill", "Water bill", "Post-paid mobile / landline bill", "Rent agreement", "Bank passbook / statement", "Voter ID", "Spouse's passport copy"];
const dobChoices = ["Birth certificate", "Class 10 / matriculation certificate", "School leaving certificate", "PAN card", "Aadhaar / e-Aadhaar", "Service record / pension order"];
const passportCenters: PassportCenter[] = [
  {id:"lalbagh",city:"Bengaluru",rpo:"Bengaluru RPO",name:"Passport Seva Kendra, Lalbagh",kind:"PSK",area:"Lalbagh Road",slots:[{id:"lal-1",label:"Tue, 03 Sep · 10:40 AM",availability:"12 slots left"},{id:"lal-2",label:"Tue, 03 Sep · 12:20 PM",availability:"8 slots left"},{id:"lal-3",label:"Wed, 04 Sep · 09:15 AM",availability:"Available"}]},
  {id:"marathahalli",city:"Bengaluru",rpo:"Bengaluru RPO",name:"Passport Seva Kendra, Marathahalli",kind:"PSK",area:"Outer Ring Road",slots:[{id:"mar-1",label:"Mon, 02 Sep · 11:10 AM",availability:"6 slots left"},{id:"mar-2",label:"Tue, 03 Sep · 09:30 AM",availability:"18 slots left"},{id:"mar-3",label:"Thu, 05 Sep · 02:00 PM",availability:"Available"}]},
  {id:"gpo",city:"Bengaluru",rpo:"Bengaluru RPO",name:"Post Office PSK, Bengaluru GPO",kind:"POPSK",area:"Raj Bhavan Road",slots:[{id:"gpo-1",label:"Wed, 04 Sep · 10:00 AM",availability:"9 slots left"},{id:"gpo-2",label:"Thu, 05 Sep · 11:40 AM",availability:"14 slots left"},{id:"gpo-3",label:"Fri, 06 Sep · 09:20 AM",availability:"Available"}]},
  {id:"shalimar",city:"Delhi",rpo:"Delhi RPO",name:"Passport Seva Kendra, Shalimar Place",kind:"PSK",area:"Outer Ring Road",slots:[{id:"sha-1",label:"Tue, 03 Sep · 09:50 AM",availability:"7 slots left"},{id:"sha-2",label:"Wed, 04 Sep · 01:10 PM",availability:"11 slots left"}]},
  {id:"herald",city:"Delhi",rpo:"Delhi RPO",name:"Passport Seva Kendra, Herald House",kind:"PSK",area:"ITO",slots:[{id:"her-1",label:"Mon, 02 Sep · 11:30 AM",availability:"5 slots left"},{id:"her-2",label:"Thu, 05 Sep · 10:20 AM",availability:"Available"}]},
  {id:"andheri",city:"Mumbai",rpo:"Mumbai RPO",name:"Passport Seva Kendra, Andheri",kind:"PSK",area:"Andheri East",slots:[{id:"and-1",label:"Wed, 04 Sep · 09:40 AM",availability:"10 slots left"},{id:"and-2",label:"Fri, 06 Sep · 12:10 PM",availability:"Available"}]},
  {id:"lower-parel",city:"Mumbai",rpo:"Mumbai RPO",name:"Passport Seva Kendra, Lower Parel",kind:"PSK",area:"Senapati Bapat Marg",slots:[{id:"low-1",label:"Tue, 03 Sep · 02:20 PM",availability:"4 slots left"},{id:"low-2",label:"Thu, 05 Sep · 11:00 AM",availability:"13 slots left"}]},
];
const appointmentCities = [...new Set(passportCenters.map(center=>center.city))];

export default function UmangPassport() {
  const [screen, setScreen] = useState<Screen>("home");
  const [form, setForm] = useState<ReissueForm>(initialForm);
  const [uploads, setUploads] = useState<Record<string, boolean>>({});
  const [documentTypes, setDocumentTypes] = useState<Record<string, string>>({ address: "Rent agreement", dob: "Birth certificate" });
  const [reviewOpen, setReviewOpen] = useState(false);
  const [resolved, setResolved] = useState(false);
  const [booked, setBooked] = useState(false);
  const [applicationStarted, setApplicationStarted] = useState(false);
  const [passportUnlocked, setPassportUnlocked] = useState(true);
  const [showPassportPin, setShowPassportPin] = useState(false);
  const [selectedCenterId, setSelectedCenterId] = useState("lalbagh");
  const [selectedCity, setSelectedCity] = useState("Bengaluru");
  const [selectedSlotId, setSelectedSlotId] = useState("lal-1");
  const [showLocationSheet, setShowLocationSheet] = useState(false);
  const [showCompanionSheet, setShowCompanionSheet] = useState(false);
  const [enteredCentre, setEnteredCentre] = useState(false);
  const [showGlobalGrievance, setShowGlobalGrievance] = useState(false);
  const [appointmentRescheduled, setAppointmentRescheduled] = useState(false);
  const [applicationSubmitted, setApplicationSubmitted] = useState(false);
  const go = (next: Screen) => { setScreen(next); window.scrollTo(0, 0); };
  const requirements = useMemo(() => buildRequirements(form), [form]);
  const selectedCenter = passportCenters.find(center => center.id === selectedCenterId) || passportCenters[0];
  const selectedSlot = selectedCenter.slots.find(slot => slot.id === selectedSlotId) || selectedCenter.slots[0];
  const chooseCenter = (id: string) => { const center = passportCenters.find(item => item.id === id) || passportCenters[0]; setSelectedCenterId(center.id); setSelectedSlotId(center.slots[0].id); setShowLocationSheet(false); };
  const chooseCity = (city:string) => { const center=passportCenters.find(item=>item.city===city) || passportCenters[0]; setSelectedCity(city); setSelectedCenterId(center.id); setSelectedSlotId(center.slots[0].id); };

  return <main className="umang-canvas"><section className="umang-phone"><PhoneStatus /><TopBar screen={screen} back={() => go(screen === "book" && booked ? "tracking" : backScreen(screen))} />
    <div className="umang-scroll">
      {screen === "home" && <UmangHome go={go} />}
      {screen === "passport" && <PassportSeva go={go} />}
      {screen === "login" && <Login go={go} />}
      {screen === "dashboard" && <Dashboard go={go} applicationStarted={applicationStarted} booked={booked} appointmentRescheduled={appointmentRescheduled} applicationSubmitted={applicationSubmitted} startApplication={()=>setApplicationStarted(true)} passportUnlocked={passportUnlocked} unlockPassport={()=>setShowPassportPin(true)} />}
      {screen === "questions" && <Questions form={form} setForm={setForm} go={go} />}
      {screen === "documents" && <Documents requirements={requirements} uploads={uploads} setUploads={setUploads} documentTypes={documentTypes} setDocumentTypes={setDocumentTypes} go={go} />}
      {screen === "review" && <Review requirements={requirements} documentTypes={documentTypes} setDocumentTypes={setDocumentTypes} open={reviewOpen} setOpen={setReviewOpen} resolved={resolved} setResolved={setResolved} appointmentRescheduled={appointmentRescheduled} go={go} />}
      {screen === "book" && <Booking booked={booked} setBooked={setBooked} go={go} city={selectedCity} chooseCity={chooseCity} center={selectedCenter} slot={selectedSlot} selectedSlotId={selectedSlotId} setSelectedSlotId={setSelectedSlotId} showLocationSheet={showLocationSheet} setShowLocationSheet={setShowLocationSheet} chooseCenter={chooseCenter} showCompanionSheet={showCompanionSheet} setShowCompanionSheet={setShowCompanionSheet} enteredCentre={enteredCentre} setEnteredCentre={setEnteredCentre} appointmentRescheduled={appointmentRescheduled} rescheduleForDocuments={()=>{setAppointmentRescheduled(true);setResolved(false);go("review")}} rescheduleByCitizen={()=>{setAppointmentRescheduled(true);go("tracking")}} completeReturnAppointment={()=>{setApplicationSubmitted(true);go("tracking")}} />}
      {screen === "companion" && <Companion go={go} />}
      {screen === "live" && <LiveVisit go={go} />}
      {screen === "tracking" && <Tracking go={go} center={selectedCenter} slot={selectedSlot} appointmentRescheduled={appointmentRescheduled} applicationSubmitted={applicationSubmitted} />}
    </div>{screen !== "home"&&<Powered />}{screen !== "home"&&<button className="global-grievance" aria-label="Report a Passport Seva problem" onClick={()=>setShowGlobalGrievance(true)}>!</button>}{screen === "home" && <BottomNav />}{showPassportPin && <PassportPinSheet close={()=>setShowPassportPin(false)} unlock={()=>{setPassportUnlocked(true);setShowPassportPin(false)}} />}{showGlobalGrievance&&<GrievanceSheet close={()=>setShowGlobalGrievance(false)}/>} 
  </section></main>;
}

function backScreen(screen: Screen): Screen { if (screen === "passport") return "home"; if (screen === "login") return "passport"; if (screen === "dashboard") return "passport"; if (screen === "questions") return "dashboard"; if (screen === "documents") return "questions"; if (screen === "review") return "documents"; if (screen === "book") return "review"; if (screen === "companion") return "book"; if (screen === "live") return "companion"; if (screen === "tracking") return "dashboard"; return "home"; }
function PhoneStatus(){return <div className="phone-status"><b>5:10</b><span>▮▮▮　⌁　<span className="battery">86</span></span></div>}
function TopBar({screen,back}:{screen:Screen;back:()=>void}) { const simple=screen === "home"; const title=screen === "passport" ? "Passport Seva" : screen === "dashboard" ? "Passport services" : screen === "questions" ? "Reissue passport" : screen === "documents" ? "Required documents" : screen === "review" ? "Document review" : screen === "book" || screen === "companion" || screen === "live" ? "My appointment" : screen === "tracking" ? "Track application" : "Passport Seva"; return <header className={simple?"umang-top home-top":"umang-top"}>{simple?<><div className="government-lockup"><span className="india-mark">♜</span><span className="umang-hand">☝</span></div><div className="home-header-actions"><button aria-label="WhatsApp">◉</button><button aria-label="Language">अ</button><button aria-label="Notifications">●</button><button className="profile-action" aria-label="Profile">AJ<i>≡</i></button></div></>:<><button onClick={back} className="back" aria-label="Back">‹</button><h1>{title}</h1><button className="more" aria-label="More options">⋮</button></>}</header>}
function BottomNav(){return <nav className="umang-nav home-nav"><button className="active">⌂<span>myUmang</span></button><button>⠿<span>Services</span></button><button>▣<span>DigiLocker</span></button><button>▣<span>Schemes</span></button><button className="bank-partner"><b>BOI★</b></button></nav>}
function Powered(){return <div className="powered">Powered by <b>Passport Seva</b></div>}

function UmangHome({go}:{go:(p:Screen)=>void}){return <section className="home-screen umang-home-v2">
  <div className="umang-search home-search"><span>Search for &quot;Aadhaar Services&quot;</span><i>⌕</i><b>🎙</b></div>
  <h1 className="home-greeting">👋 Hey, 9755071804</h1>
  <button className="passport-carousel" onClick={()=>go("passport")}><div className="carousel-copy"><small>NEW ON UMANG</small><h2>Passport services are<br/><em>completely online.</em></h2><p>Renew, prepare, visit and track your passport in one journey.</p><b>Explore Passport Seva　→</b></div><div className="carousel-art"><span>♜</span></div></button>
  <div className="home-dots"><i className="active"/><i/><i/><i/></div>
  <button className="digipin home-digipin"><span>✓</span><b>Know your DIGIPIN</b><em>→</em></button>
  <section className="home-content-section quick-services-section"><h2>🔗 Quick Services</h2><div className="quick-grid"><Quick icon="⌁" name="TOTP\nAuthenticator" color="orange"/><Quick icon="♥" name="Health" color="green"/><Quick icon="☀" name="Emergency" color="red"/><Quick icon="✈" name="Travel" color="purple"/></div></section>
  <section className="face-id-card"><div><h2>Enable <em>Face ID</em> for Faster,<br/>Safer Access</h2><p>Log in securely with your Face ID</p><button>Activate Face Id</button></div><div className="face-phone"><span>⌗</span></div></section>
  <section className="home-content-section"><h2>Recently Used Services</h2><div className="recent-services"><HomeService icon="PS" name="Passport\nSeva" tone="passport" onClick={()=>go("passport")}/><HomeService icon="14404" name="National Consumer\nHelpline" tone="consumer"/><HomeService icon="BN" name="DBN\nBharatNet" tone="bharatnet"/></div></section>
  <section className="home-content-section documents-home"><h2>☁ My Documents</h2><div className="home-documents"><HomeDocument icon="▤" name="APAAR ID"/><HomeDocument icon="▣" name="Aadhaar\nCard"/><HomeDocument icon="▥" name="Class XII\nMarksheet"/><HomeDocument icon="▧" name="Covid Vaccine\nCertificate"/></div></section>
  <section className="financial-card"><div><h2>Financial Calculator</h2><p>Get instant insights to make smarter money calculations.</p><button>Calculate Now</button></div><span>⌨</span></section>
  <section className="home-content-section helpline-section"><h2>📞 Essential Helpline Numbers</h2><div className="helpline-grid"><Helpline icon="🧑‍🌾" name="Farmers"/><Helpline icon="🧓" name="Senior\nCitizen"/><Helpline icon="🎓" name="Student"/><Helpline icon="👩‍👧" name="Women\n& Child"/><Helpline icon="🧰" name="Health"/><Helpline icon="👮" name="Police"/><Helpline icon="🚆" name="Indian\nRailways"/></div></section>
  <section className="job-card"><div><h2>Job Opportunities</h2><p>Explore job openings across departments & projects</p><button>View Jobs</button></div><span>👥</span></section>
</section>}
function Quick({icon,name,color}:{icon:string;name:string;color:string}){return <button className="quick"><span className={`quick-icon ${color}`}>{icon}</span><b>{name.split("\n").map((x,i)=><span className="quick-line" key={`${x}-${i}`}>{x}{i<name.split("\n").length-1&&<br/>}</span>)}</b></button>}
function HomeService({icon,name,tone,onClick}:{icon:string;name:string;tone:string;onClick?:()=>void}){return <button className="home-service" onClick={onClick}><span className={tone}>{icon}</span><b>{name.split("\n").map((line,index)=><span key={line}>{line}{index<name.split("\n").length-1&&<br/>}</span>)}</b></button>}
function HomeDocument({icon,name}:{icon:string;name:string}){return <button className="home-document"><span>{icon}</span><b>{name.split("\n").map((line,index)=><span key={line}>{line}{index<name.split("\n").length-1&&<br/>}</span>)}</b></button>}
function Helpline({icon,name}:{icon:string;name:string}){return <button className="helpline"><span>{icon}</span><b>{name.split("\n").map((line,index)=><span key={line}>{line}{index<name.split("\n").length-1&&<br/>}</span>)}</b></button>}

function PassportSeva({go}:{go:(p:Screen)=>void}){return <section className="passport-service"><div className="service-hero"><div className="language">English⌄</div><div className="ps-brand"><span>♜</span><div><b>Passport Seva</b><small>Government of India</small></div></div></div><div className="service-body"><div className="service-search">Search services here...</div><article className="digilocker-connect-banner"><small>▣ DigiLocker connected sign-in</small><h2>Sign in to Passport Seva with DigiLocker</h2><p>Use your verified DigiLocker identity to fetch your existing passport record and continue without creating another account.</p><button onClick={()=>go("login")}>Sign in with DigiLocker</button></article><h2>General Services</h2><GeneralServices /></div></section>}
function GeneralServices(){return <><ServiceRow icon="▤" name="Locate Centre" color="blue"/><ServiceRow icon="▧" name="Fee Calculator" color="gold"/><ServiceRow icon="▤" name="Status Tracker" color="green"/><ServiceRow icon="▦" name="Check Appointment Availability" color="pink"/><ServiceRow icon="♙" name="Document Advisor" color="purple"/></>}
function ServiceRow({icon,name,color}:{icon:string;name:string;color:string}){return <button className="service-row"><span className={color}>{icon}</span><b>{name}</b><i>ⓘ</i></button>}

function Login({go}:{go:(p:Screen)=>void}){return <section className="login-screen"><div className="login-lock">▣</div><h2>Continue to Passport Seva</h2><p>Access your passport services securely through UMANG.</p><button className="login-option primary-login" onClick={()=>go("dashboard")}><span>▣</span><div><b>Sign in with DigiLocker</b><small>Use verified identity and document records</small></div><i>›</i></button><div className="login-or"><span/>OR<span/></div><button className="login-option" onClick={()=>go("dashboard")}><span>✉</span><div><b>Sign in with email</b><small>Your account will be synced with DigiLocker</small></div><i>›</i></button></section>}

function Dashboard({go,applicationStarted,booked,appointmentRescheduled,applicationSubmitted,startApplication}:{go:(p:Screen)=>void;applicationStarted:boolean;booked:boolean;appointmentRescheduled:boolean;applicationSubmitted:boolean;startApplication:()=>void;passportUnlocked:boolean;unlockPassport:()=>void}){return <section className="dashboard"><p className="eyebrow">PASSPORT SEVA ON UMANG</p><h2>Good afternoon, Anushka</h2><PassportBook/><h3>Passport services</h3><div className="passport-actions"><button onClick={()=>{startApplication();go("questions")}}><span>↻</span><b>Reissue passport</b><small>Renew, update or replace</small></button><button className="coming"><span>◌</span><b>Apply for visa</b><small>Coming soon</small></button></div>{applicationStarted&&<button className="ongoing-application" onClick={()=>go(booked?"tracking":"questions")}><span className="ongoing-icon">↻</span><div><small>{applicationSubmitted?"APPLICATION SUBMITTED":booked?"APPLICATION IN PROGRESS":"ONGOING APPLICATION"}</small><b>Passport reissue</b><p>{applicationSubmitted?"Police verification in progress":booked?(appointmentRescheduled?"Appointment rescheduled · View latest status":"Appointment scheduled · Track application"):"Draft saved · Complete your assessment"}</p></div><i>{booked?"Track":"Resume"}　›</i></button>}<h3>General services</h3><GeneralServices /></section>}
function PassportBook(){return <article className="passport-profile-card"><div className="profile-card-top"><div><small>PASSPORT NUMBER</small><b>P•••••482</b></div><em>Powered by DigiLocker</em></div><div className="profile-card-grid"><span><small>VALID TILL</small><b>14 May 2032</b></span><span><small>STATUS</small><b>Valid</b></span><span><small>ISSUED AT</small><b>Bengaluru</b></span><span><small>TYPE</small><b>Ordinary</b></span></div><button>View passport record</button></article>}
function PassportPinSheet({close,unlock}:{close:()=>void;unlock:()=>void}){const [dateOfBirth,setDateOfBirth]=useState("");const dobComplete=dateOfBirth.replace(/\D/g,"").length===8;return <div className="sheet-overlay"><section className="bottom-sheet pin-sheet"><button className="sheet-close" onClick={close}>×</button><span className="sheet-handle"/><span className="pin-lock">⌑</span><h2>Unlock your passport</h2><p>Enter the date of birth printed on your passport.</p><label>Date of birth<input aria-label="Date of birth" type="text" inputMode="numeric" placeholder="DD/MM/YYYY" maxLength={10} value={dateOfBirth} onChange={event=>setDateOfBirth(event.target.value)}/></label><button className="flow-cta" disabled={!dobComplete} onClick={unlock}>Unlock passport</button></section></div>}

function Questions({form,setForm,go}:{form:ReissueForm;setForm:(value:ReissueForm)=>void;go:(p:Screen)=>void}) {
  const set = (key: Exclude<keyof ReissueForm,"reasons">, value: string) => setForm({...form,[key]:value});
  const toggleReason = (value:string) => { const reasons = form.reasons.includes(value) ? form.reasons.filter(item=>item!==value) : [...form.reasons.filter(item=>item!=="None of the above"),value]; setForm({...form,reasons:value === "None of the above" ? [value] : reasons}); };
  const damaged = form.reasons.includes("Damaged passport");
  const lost = form.reasons.includes("Lost / stolen passport");
  const changingDetails = form.reasons.includes("Change in personal particulars");
  const incidentDetailsReady = (!damaged || Boolean(form.damageLevel && form.abroad)) && (!lost || Boolean(form.abroad && form.policeReport)) && (!changingDetails || Boolean(form.personalChange));
  const baseComplete = Boolean(form.application && form.applicant && form.employment && form.address && form.nonEcr && form.reasons.length);
  const valid = Boolean(baseComplete && incidentDetailsReady && form.courtCase);
  const progress=form.courtCase?4:form.reasons.length?3:form.applicant?2:1;
  return <section className="flow-screen assessment-screen"><p className="step-label">REISSUE ASSESSMENT</p><div className="assessment-progress" aria-label={`Step ${progress} of 4`}>{[1,2,3,4].map(step=><i className={step<=progress?"active":""} key={step}/>)}</div><h2>Tell us about your passport</h2><p>Answer the questions below and we&apos;ll generate a personalised document pack before you book.</p>
    <OptionQuestion title="Application type" required values={["Normal", "Tatkaal"]} chosen={form.application} choose={(v)=>set("application",v)} />
    {form.application&&<div className="conditional-question"><OptionQuestion title="Applicant category" required values={["Adult", "Minor"]} chosen={form.applicant} choose={(v)=>set("applicant",v)} /></div>}
    {form.applicant&&<div className="conditional-question"><OptionQuestion title="Employment type" required values={["Government / PSU / statutory body", "Retired government official", "Private / self-employed / other"]} chosen={form.employment} choose={(v)=>set("employment",v)} /></div>}
    {form.employment&&<div className="conditional-question"><OptionQuestion title="Is your present address different from the existing passport?" required values={["Yes, it has changed", "No, it is the same"]} chosen={form.address} choose={(v)=>set("address",v)} /></div>}
    {form.address&&<div className="conditional-question"><OptionQuestion title="Are you eligible for Non-ECR?" required values={["Yes", "No", "I’m not sure"]} chosen={form.nonEcr} choose={(v)=>set("nonEcr",v)} /></div>}
    {form.nonEcr&&<div className="conditional-question"><MultiQuestion title="Why do you need a reissue? Select every applicable reason." required values={reissueReasons} chosen={form.reasons} toggle={toggleReason}/></div>}
    {changingDetails&&<div className="conditional-question"><OptionQuestion title="Which detail needs to change?" required values={["Name / surname", "Date or place of birth", "Spouse name", "Gender", "Appearance / signature", "Other personal detail"]} chosen={form.personalChange} choose={(v)=>set("personalChange",v)} /></div>}
    {damaged&&<div className="conditional-question"><OptionQuestion title="How much damage does the passport have?" required values={["Minor — all details are readable", "Major — pages or cover are torn", "Severe — passport is not recognisable"]} chosen={form.damageLevel} choose={(v)=>set("damageLevel",v)} /></div>}
    {((damaged&&form.damageLevel)||lost)&&<div className="conditional-question"><OptionQuestion title={damaged&&lost?"Was the passport lost or damaged outside India?":damaged?"Was the passport damaged outside India?":"Was the passport lost or stolen outside India?"} required values={["No", "Yes"]} chosen={form.abroad} choose={(v)=>set("abroad",v)} /></div>}
    {lost&&form.abroad&&<div className="conditional-question"><OptionQuestion title="Do you have an FIR or police report?" required values={["Yes, I have it", "Not yet"]} chosen={form.policeReport} choose={(v)=>set("policeReport",v)} /></div>}
    {baseComplete&&incidentDetailsReady&&<div className="conditional-question"><OptionQuestion title="Do you have an ongoing court case or a court restriction relating to travel?" required values={["No", "Yes"]} chosen={form.courtCase} choose={(v)=>set("courtCase",v)} /></div>}
    {form.courtCase&&<><p className="form-note">This is a prototype pre-check. Passport Seva may ask for additional documents after review.</p><button className="flow-cta" disabled={!valid} onClick={()=>go("documents")}>Generate my document list　→</button></>}
  </section>
}
function OptionQuestion({title,values,chosen,choose,required}:{title:string;values:string[];chosen:string;choose:(x:string)=>void;required?:boolean}){return <div className="question"><b>{title}{required&&<em>*</em>}</b><div>{values.map(x=><button type="button" onClick={()=>choose(x)} className={chosen===x?"chosen":""} key={x}><i>{chosen===x?"●":"○"}</i><span><strong>{x}</strong>{answerHint(x)&&<small>{answerHint(x)}</small>}</span></button>)}</div></div>}
function MultiQuestion({title,values,chosen,toggle,required}:{title:string;values:string[];chosen:string[];toggle:(x:string)=>void;required?:boolean}){return <div className="question multi-question"><b>{title}{required&&<em>*</em>}</b><div>{values.map(x=><button type="button" onClick={()=>toggle(x)} className={chosen.includes(x)?"chosen":""} key={x}><i>{chosen.includes(x)?"✓":"□"}</i><span><strong>{x}</strong>{answerHint(x)&&<small>{answerHint(x)}</small>}</span></button>)}</div></div>}
function answerHint(value:string){const hints:Record<string,string>={Normal:"Standard Passport Seva processing",Tatkaal:"Expedited processing with applicable fee",Adult:"Applicant is 18 years or older",Minor:"Applicant is below 18 years","Damaged passport":"Passport is physically damaged or unreadable","Lost / stolen passport":"The existing passport cannot be produced","Validity due to expire":"Renew before the current passport expires","Validity expired":"The existing passport has already expired","Change in personal particulars":"Update name, address or another recorded detail","Exhaustion of pages":"Visa pages are no longer available","Yes, it has changed":"A new present-address proof will be required","No, it is the same":"Your current address matches the passport record"};return hints[value]||""}

function buildRequirements(form: ReissueForm): Requirement[] {
  const lost = form.reasons.includes("Lost / stolen passport");
  const damaged = form.reasons.includes("Damaged passport");
  const hasIncident = lost || damaged;
  const hasChange = form.reasons.includes("Change in personal particulars");
  const needsAddress = form.address === "Yes, it has changed" || hasIncident || hasChange;
  const passportRequirement = lost
    ? {id:"passport",title:"Lost passport record or available copies",detail:"Attach a copy of the lost passport if available, including its first two and last two pages and ECR / Non-ECR page. The original is not expected for a lost or stolen passport.",tag:"Mandatory"}
    : damaged
      ? {id:"passport",title:"Damaged passport and readable copies",detail:`Bring the original damaged passport. Attach every readable identity, observation and validity page. Damage reported: ${form.damageLevel || "not specified"}.`,tag:"Mandatory"}
      : {id:"passport",title:"Existing passport and copies",detail:"Bring the original existing passport to the PSK. Attach clearly readable, self-attested copies of the first two and last two pages, ECR / Non-ECR page, observation page and any validity-extension page.",tag:"Mandatory"};
  const items: Requirement[] = [
    passportRequirement,
    {id:"address",title:"Proof of present address",detail:needsAddress ? "Attach one accepted document that shows the current address entered in this application." : "Attach one accepted proof of your present address, even if it matches the existing passport.",choices:addressChoices,tag:"Mandatory"},
    {id:"dob",title:"Proof of date of birth",detail:"Attach one accepted proof that supports the date of birth in the application.",choices:dobChoices,tag:"Mandatory"},
  ];
  if (hasIncident) items.push({id:"affidavit",title:"Affidavit for lost / damaged passport",detail:"Complete the declaration describing how and where the passport was lost or damaged, then attach the signed Annexure F.",tag:"Mandatory",downloadHref:"https://passportindia.gov.in/AppOnlineProject/pdf/Revised_Annexures.pdf",downloadLabel:"Download Annexure F · official template"});
  if (lost) items.push({id:"fir",title:"FIR / police report",detail:form.policeReport === "Not yet" ? "Obtain and attach the FIR or police report before submitting the document pack." : "Attach the FIR or police report for the lost or stolen passport.",tag:"Mandatory"});
  if (hasIncident && form.abroad === "Yes") items.push({id:"emergency",title:"Emergency Certificate, if issued",detail:"Attach the Emergency Certificate or temporary travel document issued after the incident abroad, if one was provided.",tag:"Required when applicable"});
  if (hasChange) { const changeDetail = form.personalChange === "Name / surname" ? "Attach the supporting record for the name change, plus two public or school documents in the changed name where applicable." : form.personalChange === "Date or place of birth" ? "Attach the supporting birth record and the required declaration explaining the correction." : "Attach the official record that supports the requested change in personal particulars."; items.push({id:"change",title:"Proof for the requested change",detail:changeDetail,tag:"Mandatory"}); }
  if (form.applicant === "Minor") items.push({id:"minor",title:"Parent / guardian declaration",detail:"Attach the applicable parent or guardian declaration and supporting documents for the minor applicant.",tag:"Mandatory"});
  if (form.employment === "Government / PSU / statutory body") items.push({id:"noc",title:"Employer clearance",detail:"Attach the applicable No Objection Certificate or Prior Intimation letter from your employer.",tag:"Required for your employment type"});
  if (form.courtCase === "Yes") items.push({id:"court",title:"Court order and undertaking",detail:"Attach the relevant court order(s) and undertaking that cover the pending case and travel permission.",tag:"Mandatory"});
  return items;
}

function Documents({requirements,uploads,setUploads,documentTypes,setDocumentTypes,go}:{requirements:Requirement[];uploads:Record<string,boolean>;setUploads:(v:Record<string,boolean>)=>void;documentTypes:Record<string,string>;setDocumentTypes:(v:Record<string,string>)=>void;go:(p:Screen)=>void}) { const complete = requirements.every(requirement=>uploads[requirement.id]); return <section className="flow-screen documents-screen"><p className="step-label">YOUR PERSONALISED DOCUMENT LIST</p><h2>Attach your documents</h2><p>Upload each item before requesting a review. You will still carry the originals to your appointment.</p><div className="requirements-list">{requirements.map(requirement=><RequirementCard key={requirement.id} requirement={requirement} attached={Boolean(uploads[requirement.id])} selectedType={documentTypes[requirement.id] || requirement.choices?.[0] || ""} setType={(value)=>setDocumentTypes({...documentTypes,[requirement.id]:value})} toggle={()=>setUploads({...uploads,[requirement.id]:!uploads[requirement.id]})}/>)}</div><p className="form-note">A DigiLocker record can help pre-fill details; it does not replace originals required at the Passport Seva Kendra.</p>{complete&&<button className="flow-cta" onClick={()=>go("review")}>Submit for document review　→</button>}</section>}
function RequirementCard({requirement,attached,selectedType,setType,toggle}:{requirement:Requirement;attached:boolean;selectedType:string;setType:(value:string)=>void;toggle:()=>void}) {return <article className="requirement"><div className="requirement-head"><span className={attached?"done":"pending"}>{attached?"✓":"!"}</span><div><b>{requirement.title}</b><em>{requirement.tag}</em></div></div><p>{requirement.detail}</p>{requirement.choices&&<label>Document you&apos;re attaching<select value={selectedType} onChange={event=>setType(event.target.value)}>{requirement.choices.map(choice=><option key={choice}>{choice}</option>)}</select></label>}{requirement.downloadHref&&<a className="annexure-download" href={requirement.downloadHref} target="_blank" rel="noreferrer"><span>⇩</span><div><b>{requirement.downloadLabel}</b><small>Passport Seva document · PDF</small></div><i>›</i></a>}<div className="attachment-row"><span>{attached ? `${fileName(requirement.id, selectedType)} attached` : "No document attached"}</span><button type="button" onClick={toggle}>{attached ? "Change" : "Attach document"}</button></div></article>}
function fileName(id:string,type:string){const normalized=(type || id).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");return `${normalized || id}.pdf`}

function Review({requirements,documentTypes,setDocumentTypes,open,setOpen,resolved,setResolved,appointmentRescheduled,go}:{requirements:Requirement[];documentTypes:Record<string,string>;setDocumentTypes:(value:Record<string,string>)=>void;open:boolean;setOpen:(v:boolean)=>void;resolved:boolean;setResolved:(v:boolean)=>void;appointmentRescheduled:boolean;go:(p:Screen)=>void}){
  const hasAffidavit = requirements.some(item=>item.id === "affidavit");
  const extraDocuments = requirements.filter(item=>!["passport","address","dob","affidavit"].includes(item.id));
  const [additionalUploads,setAdditionalUploads]=useState<Record<string,boolean>>({});
  const [primaryReuploaded,setPrimaryReuploaded]=useState(false);
  const returnReview=appointmentRescheduled;
  const additionalItems=returnReview
    ? [{id:"damage-photos",title:"Passport damage photographs",subtitle:"Attach clear photographs of the passport cover, identity page and every damaged page"}]
    : [{id:"witness",title:"Witness identity proofs",subtitle:"Self-attested ID proof for both Indian-citizen witnesses"},{id:"owner",title:"Property owner identity proof",subtitle:"One self-attested government-issued ID proof"}];
  const additionalComplete=additionalItems.every(item=>additionalUploads[item.id]);
  const readyToResubmit=primaryReuploaded&&additionalComplete;
  const intro=resolved
    ? returnReview?"Your updated documents have been verified. Your return appointment can continue.":"Your updated documents have been verified. You can now schedule your appointment."
    : returnReview?"The Passport Seva officer requested these updates before your return visit.":"We reviewed your uploads before you book an appointment.";
  return <section className="flow-screen review-screen"><p className="step-label">{returnReview?"RETURN APPOINTMENT CHECK":"PRE-APPOINTMENT CHECK"}</p><h2>{resolved?"Document review complete":"Document review"}</h2><p>{intro}</p>
    <section className="review-section"><h3>{resolved?"Verified documents":"Successfully uploaded"}</h3><div className="uploaded-list"><UploadedDocument title="Existing passport and copies" subtitle="All required pages are readable"/><UploadedDocument title="Proof of date of birth" subtitle="Details match your application"/>{returnReview&&!resolved&&<UploadedDocument title={`Proof of present address · ${documentTypes.address}`} subtitle="Verified during your earlier document review"/>}{hasAffidavit&&!returnReview&&<UploadedDocument title="Lost / damaged passport affidavit" subtitle="Completed Annexure F is attached"/>}{extraDocuments.map(item=><UploadedDocument key={item.id} title={item.title} subtitle="Document is readable and complete"/>) }{resolved&&<><UploadedDocument title={`Proof of present address · ${documentTypes.address}`} subtitle="Address and name match your application"/>{returnReview&&<UploadedDocument title="Signed Annexure F affidavit" subtitle="Every declaration page is signed and readable"/>}{additionalItems.map(item=><UploadedDocument key={item.id} title={item.title} subtitle="Verified for the updated application"/>)}</>}</div></section>
    {!resolved&&<section className="review-section"><h3>Needs attention</h3><article className={`attention-document ${primaryReuploaded?"resolved-upload":""}`}><span>{primaryReuploaded?"✓":"!"}</span><div><b>{returnReview?"Annexure F affidavit":documentTypes.address || "Proof of present address"}</b><p>{primaryReuploaded?"Updated document attached and ready to submit for verification.":returnReview?"The declaration page is missing your signature. Upload a freshly signed Annexure F before your return appointment.":"The rent agreement is missing the signatures of two Indian-citizen witnesses and does not include the property owner's identity proof."}</p><div className="repair-actions"><button onClick={()=>setPrimaryReuploaded(true)}>{primaryReuploaded?"Change upload":"Re-upload document"}</button>{returnReview?<a className="secondary" href="https://passportindia.gov.in/AppOnlineProject/pdf/Revised_Annexures.pdf" target="_blank" rel="noreferrer">Download Annexure F</a>:<button className="secondary" onClick={()=>setOpen(!open)}>Change document type</button>}</div>{!returnReview&&open&&<div className="type-change"><b>Choose another accepted proof</b>{["Aadhaar / e-Aadhaar","Bank passbook / statement","Electricity bill"].map(choice=><button key={choice} onClick={()=>{setDocumentTypes({...documentTypes,address:choice});setPrimaryReuploaded(true);setOpen(false)}}>{choice}</button>)}</div>}</div></article></section>}
    {!resolved&&<section className="review-section additional-section"><h3>Additional documents required</h3><div className="additional-upload-list">{additionalItems.map(item=><AdditionalDocument key={item.id} title={item.title} subtitle={item.subtitle} attached={Boolean(additionalUploads[item.id])} upload={()=>setAdditionalUploads({...additionalUploads,[item.id]:!additionalUploads[item.id]})}/>)}</div></section>}
    <p className="review-disclaimer">Mock pre-check outcome for this prototype. A Passport Seva officer makes the final decision and may request more records.</p>{!resolved&&readyToResubmit&&<button className="flow-cta" onClick={()=>setResolved(true)}>Submit updated documents for verification　→</button>}{resolved&&<button className="flow-cta" onClick={()=>go(appointmentRescheduled?"tracking":"book")}>{appointmentRescheduled?"Continue":"Schedule appointment"}　→</button>}
  </section>
}
function UploadedDocument({title,subtitle}:{title:string;subtitle:string}){return <div className="uploaded-document"><span>✓</span><div><b>{title}</b><small>{subtitle}</small></div></div>}
function AdditionalDocument({title,subtitle,attached,upload}:{title:string;subtitle:string;attached:boolean;upload:()=>void}){return <article className={`additional-document ${attached?"attached":""}`}><span>{attached?"✓":"+"}</span><div><b>{title}</b><small>{attached?"Document attached · ready for re-verification":subtitle}</small></div><button onClick={upload}>{attached?"Change":"Attach"}</button></article>}

function Booking({booked,setBooked,go,city,chooseCity,center,slot,selectedSlotId,setSelectedSlotId,showLocationSheet,setShowLocationSheet,chooseCenter,showCompanionSheet,setShowCompanionSheet,enteredCentre,setEnteredCentre,appointmentRescheduled,rescheduleForDocuments,rescheduleByCitizen,completeReturnAppointment}:{booked:boolean;setBooked:(v:boolean)=>void;go:(p:Screen)=>void;city:string;chooseCity:(city:string)=>void;center:PassportCenter;slot:PassportCenter["slots"][number];selectedSlotId:string;setSelectedSlotId:(id:string)=>void;showLocationSheet:boolean;setShowLocationSheet:(v:boolean)=>void;chooseCenter:(id:string)=>void;showCompanionSheet:boolean;setShowCompanionSheet:(v:boolean)=>void;enteredCentre:boolean;setEnteredCentre:(v:boolean)=>void;appointmentRescheduled:boolean;rescheduleForDocuments:()=>void;rescheduleByCitizen:()=>void;completeReturnAppointment:()=>void}){const [showCitySheet,setShowCitySheet]=useState(false);if(booked)return <MyAppointment center={center} slot={slot} qrOpen={showCompanionSheet} setQrOpen={setShowCompanionSheet} entered={enteredCentre} setEntered={setEnteredCentre} appointmentRescheduled={appointmentRescheduled} rescheduleForDocuments={rescheduleForDocuments} rescheduleByCitizen={rescheduleByCitizen} completeReturnAppointment={completeReturnAppointment} go={go}/>;return <section className="flow-screen appointment-book"><p className="step-label">SCHEDULE APPOINTMENT</p><h2>Choose a Passport Seva Kendra</h2><p>Choose your current city of residence, then select a PSK or POPSK and an available slot.</p><label className="appointment-location">Current city of residence<button type="button" onClick={()=>setShowCitySheet(true)}><span>⌖</span><b>{city}</b><i>Change　›</i></button></label><label className="psk-selection-label">Choose preferred PSK</label><button className="centre-card" onClick={()=>setShowLocationSheet(true)}><span>⌖</span><div><small>{center.kind} · {center.area}</small><b>{center.name}</b></div><i>Change PSK　›</i></button><h3>Available appointment slots</h3><div className="slot-list">{center.slots.map(item=><button className={selectedSlotId===item.id?"selected-slot":""} onClick={()=>setSelectedSlotId(item.id)} key={item.id}><b>{item.label}</b><span>{item.availability}　{selectedSlotId===item.id?"✓":"›"}</span></button>)}</div><p className="schedule-note">Availability shown is mock data. Slots differ by city and Passport Seva Kendra.</p><button className="flow-cta" onClick={()=>{setBooked(true);go("tracking")}}>Confirm {slot.label}　→</button>{showCitySheet&&<CitySheet city={city} choose={(value)=>{chooseCity(value);setShowCitySheet(false)}} close={()=>setShowCitySheet(false)}/>} {showLocationSheet&&<LocationSheet city={city} selectedId={center.id} chooseCenter={chooseCenter} close={()=>setShowLocationSheet(false)}/>}</section>}
function CitySheet({city,choose,close}:{city:string;choose:(city:string)=>void;close:()=>void}){return <div className="sheet-overlay"><section className="bottom-sheet city-sheet"><button className="sheet-close" onClick={close}>×</button><span className="sheet-handle"/><p className="step-label">RESIDENTIAL JURISDICTION</p><h2>Choose your current city</h2><p>Select the city where you live and can provide present-address proof.</p><div className="city-options">{appointmentCities.map(item=><button className={item===city?"selected-city":""} onClick={()=>choose(item)} key={item}><span>⌖</span><div><b>{item}</b><small>{passportCenters.find(center=>center.city===item)?.rpo}</small></div><i>{item===city?"✓":"›"}</i></button>)}</div></section></div>}
function LocationSheet({city,selectedId,chooseCenter,close}:{city:string;selectedId:string;chooseCenter:(id:string)=>void;close:()=>void}){const centers=passportCenters.filter(center=>center.city===city);return <div className="sheet-overlay"><section className="bottom-sheet location-sheet"><button className="sheet-close" onClick={close}>×</button><span className="sheet-handle"/><p className="step-label">{centers[0]?.rpo.toUpperCase()}</p><h2>Choose a Passport Seva Kendra</h2><p>Each centre in {city} has its own appointment availability.</p><div className="center-options">{centers.map(center=><button onClick={()=>chooseCenter(center.id)} className={selectedId===center.id?"selected-center":""} key={center.id}><span>⌖</span><div><small>{center.kind} · {center.area}</small><b>{center.name}</b><em>Earliest: {center.slots[0].label}</em></div><i>{selectedId===center.id?"✓":"›"}</i></button>)}</div></section></div>}
function MyAppointment({center,slot,qrOpen,setQrOpen,entered,setEntered,appointmentRescheduled,rescheduleForDocuments,rescheduleByCitizen,completeReturnAppointment}:{center:PassportCenter;slot:PassportCenter["slots"][number];qrOpen:boolean;setQrOpen:(v:boolean)=>void;entered:boolean;setEntered:(v:boolean)=>void;appointmentRescheduled:boolean;rescheduleForDocuments:()=>void;rescheduleByCitizen:()=>void;completeReturnAppointment:()=>void;go:(p:Screen)=>void}) {
  const [visitState,setVisitState]=useState<VisitState>(appointmentRescheduled?"rescheduled":entered?"checkedIn":"scheduled");
  const [showReschedule,setShowReschedule]=useState(false);
  const [showGrievance,setShowGrievance]=useState(false);
  useEffect(()=>{if(visitState!=="checkedIn")return;const timer=window.setTimeout(()=>setVisitState("documentsPending"),4200);return()=>window.clearTimeout(timer)},[visitState]);
  const displaySlot=visitState==="rescheduled"?{...slot,id:"rescheduled",label:"Thu, 05 Sep · 09:30 AM",availability:"Rescheduled"}:slot;
  const title=visitState==="scheduled"?"Appointment scheduled":visitState==="rescheduled"?"Appointment rescheduled":visitState==="documentsPending"?"Documents need attention":"Appointment in progress";
  return <section className="flow-screen my-appointment"><p className="step-label">MY APPOINTMENT</p><h2>{title}</h2><p>{visitState==="scheduled"?"Your visit is confirmed. Keep your token and QR ready when you arrive.":visitState==="rescheduled"?"Your new appointment is confirmed. Completed counter checks have been preserved.":visitState==="documentsPending"?"Your application is paused until the pending documents are ready.":"Your entry is confirmed. Follow each counter below."}</p>
    <article className="scheduled-card"><div className="scheduled-status"><span>#</span><div><small>TOKEN NUMBER</small><b>BNC-048</b></div><em>{visitState==="rescheduled"?"RESCHEDULED":visitState==="scheduled"?"VISIT CONFIRMED":"IN PROGRESS"}</em></div><AppointmentDetailRow icon="◷" label="Appointment time" value={displaySlot.label}/><AppointmentDetailRow icon="◴" label="Reporting time" value={reportingTime(displaySlot.label)}/><AppointmentDetailRow icon="⌖" label="Location" value={`${center.name} · ${center.area}`}/><button className="show-qr" onClick={()=>setQrOpen(true)}>▦　Show QR</button></article>
    {visitState==="documentsPending"&&<section className="pending-status"><span>!</span><div><small>APPLICATION PAUSED AT COUNTER C</small><b>A few supporting documents are pending submission</b><p>Prepare the requested records and book a return appointment. Your completed checks will not be repeated.</p><button onClick={rescheduleForDocuments}>Reschedule appointment　→</button></div></section>}
    {visitState==="rescheduled"&&<section className="priority-return"><span>↻</span><div><small>PRIORITY RETURN JOURNEY</small><b>Report directly to Counter C</b><p>Counter A and Counter B are already complete.</p></div></section>}
    <section className="appointment-section"><h3>{visitState==="scheduled"?"Application progress":"Counter progress"}</h3><div className="timeline">{visitState==="scheduled"?<><Time done title="Appointment booked" text={`${displaySlot.label} · ${center.area}`}/><Time done title="Documents reviewed" text="Your online document pack is ready"/><Time active title="Visit and check-in" text={`Report by ${reportingTime(displaySlot.label)}`}/></>:visitState==="rescheduled"?<><Time done title="Counter A · Intake" text="Completed on the earlier visit"/><Time done title="Counter B · Verification" text="Completed on the earlier visit"/><Time active title="Counter C · Decision" text="Report here directly on your return"/></>:<><Time done title="Counter A · Intake" text="Token and documents received"/><Time done title="Counter B · Verification" text="Identity checks completed"/><Time active title="Counter C · Decision" text={visitState==="documentsPending"?"Paused — supporting documents required":"Officer review in progress"}/></>}</div></section>
    <AppointmentPageList title="Document guide" items={["Existing passport and self-attested copies","Original proof of present address","Original proof of date of birth","Affidavit and supporting records, if applicable"]}/><AppointmentPageList title="Facilities at the centre" items={["Accessible entrance","Token help desk","Seating area and drinking water","Parking nearby"]} icons={["♿","ⓘ","▰","P"]}/>
    <section className="visit-actions"><button onClick={()=>setShowReschedule(true)}>↻<span><b>Reschedule appointment</b><small>Tell us why and choose a return visit</small></span><i>›</i></button><button className="cancel-action">×<span><b>Cancel appointment</b><small>Cancellation terms may apply</small></span><i>›</i></button><button>?<span><b>Frequently asked questions</b><small>Prepare for your PSK visit</small></span><i>›</i></button></section>
    <button className="grievance-entry" onClick={()=>setShowGrievance(true)}><span>!</span><div><b>Report a problem on UMANG</b><small>Official behaviour, missing facilities or a bribe request</small></div><i>›</i></button>
    {visitState==="checkedIn"&&<p className="live-refresh">● Live counter status will refresh automatically</p>}{visitState==="documentsPending"&&<button className="flow-cta" onClick={rescheduleForDocuments}>Reschedule appointment　→</button>}{visitState==="rescheduled"&&<button className="flow-cta" onClick={completeReturnAppointment}>Continue　→</button>}
    {qrOpen&&<QrSheet center={center} slot={displaySlot} entered={visitState!=="scheduled"} close={()=>setQrOpen(false)} scan={()=>{setEntered(true);setVisitState("checkedIn");setQrOpen(false)}}/>}{showReschedule&&<RescheduleSheet close={()=>setShowReschedule(false)} confirm={rescheduleByCitizen}/>} {showGrievance&&<GrievanceSheet close={()=>setShowGrievance(false)}/>}</section>
}
function AppointmentDetailRow({icon,label,value}:{icon:string;label:string;value:string}){return <div className="appointment-detail"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>}
function AppointmentPageList({title,items,icons}:{title:string;items:string[];icons?:string[]}){return <section className="appointment-page-list"><h3>{title}</h3>{items.map((item,index)=><div key={item}><span>{icons?.[index]||"✓"}</span><b>{item}</b></div>)}</section>}
function QrSheet({center,slot,entered,close,scan}:{center:PassportCenter;slot:PassportCenter["slots"][number];entered:boolean;close:()=>void;scan:()=>void}){return <div className="sheet-overlay"><section className="bottom-sheet qr-sheet"><button className="sheet-close" onClick={close}>×</button><span className="sheet-handle"/><p className="step-label">ENTRY PASS</p><h2>Scan at the PSK entrance</h2><p>Token BNC-048 · Report by {reportingTime(slot.label)}</p><QrCode/><b>{center.name}</b><small>{slot.label}</small>{!entered&&<button className="flow-cta" onClick={scan}>Simulate entry scan　→</button>}</section></div>}
function RescheduleSheet({close,confirm}:{close:()=>void;confirm:()=>void}){const [reason,setReason]=useState("");const reasons=["Appointment is taking longer than expected","I have an important task","Required documents are pending"];return <div className="sheet-overlay"><section className="bottom-sheet reschedule-sheet"><button className="sheet-close" onClick={close}>×</button><span className="sheet-handle"/><p className="step-label">RESCHEDULE VISIT</p><h2>Why do you need another slot?</h2><p>This helps Passport Seva understand delays and improve centre operations.</p><div className="reason-options">{reasons.map(item=><button className={reason===item?"selected-reason":""} onClick={()=>setReason(item)} key={item}><span>{reason===item?"●":"○"}</span>{item}</button>)}</div><div className="next-slot"><small>NEXT AVAILABLE RETURN SLOT</small><b>Thu, 05 Sep · 09:30 AM</b><p>Report by 09:05 AM · Counter A and B will remain complete.</p></div><button className="flow-cta" disabled={!reason} onClick={confirm}>Confirm rescheduled appointment　→</button></section></div>}
function GrievanceSheet({close}:{close:()=>void}){const [category,setCategory]=useState("");const [submitted,setSubmitted]=useState(false);const categories=["Poor behaviour by a centre official","A stated facility was unavailable","A police officer requested a bribe","Another Passport Seva issue"];return <div className="sheet-overlay"><section className="bottom-sheet grievance-sheet"><button className="sheet-close" onClick={close}>×</button><span className="sheet-handle"/>{submitted?<div className="grievance-success"><span>✓</span><h2>Grievance recorded</h2><p>Reference UM-PS-20481 has been created. Updates will appear securely in UMANG.</p><button className="flow-cta" onClick={close}>Done</button></div>:<><p className="step-label">UMANG GRIEVANCE SUPPORT</p><h2>Report a Passport Seva problem</h2><p>Your report can cover centre conduct, missing facilities or corruption during police verification.</p><div className="reason-options">{categories.map(item=><button className={category===item?"selected-reason":""} onClick={()=>setCategory(item)} key={item}><span>{category===item?"●":"○"}</span>{item}</button>)}</div>{category&&<label className="grievance-note">Add details<textarea aria-label="Grievance details" placeholder="Tell us what happened, where and when"/></label>}<button className="flow-cta" disabled={!category} onClick={()=>setSubmitted(true)}>Submit grievance securely　→</button></>}</section></div>}
function QrCode(){const size=29;const finder=(x:number,y:number,ox:number,oy:number)=>{const dx=x-ox,dy=y-oy;if(dx<0||dy<0||dx>6||dy>6)return false;return dx===0||dy===0||dx===6||dy===6||(dx>=2&&dx<=4&&dy>=2&&dy<=4)};const reserved=(x:number,y:number)=>((x<8&&y<8)||(x>=size-8&&y<8)||(x<8&&y>=size-8)||(x>=18&&x<=22&&y>=18&&y<=22)||x===6||y===6);const modules:Array<[number,number]>=[];for(let y=0;y<size;y++)for(let x=0;x<size;x++){let dark=false;if(x<7&&y<7)dark=finder(x,y,0,0);else if(x>=size-7&&y<7)dark=finder(x,y,size-7,0);else if(x<7&&y>=size-7)dark=finder(x,y,0,size-7);else if(x>=18&&x<=22&&y>=18&&y<=22){const dx=Math.abs(x-20),dy=Math.abs(y-20);dark=Math.max(dx,dy)===2||(dx===0&&dy===0)}else if(x===6||y===6)dark=(x+y)%2===0;else if(!reserved(x,y))dark=((x*11+y*7+x*y*3+17)%13)<6;if(dark)modules.push([x,y])}return <svg className="entry-qr" viewBox="0 0 37 37" aria-label="Entry QR code"><rect width="37" height="37" rx="1.2" fill="white"/>{modules.map(([x,y])=><rect key={`${x}-${y}`} x={x+4} y={y+4} width="1.04" height="1.04" fill="#0b0c0e"/>)}</svg>}
function reportingTime(slot:string){const match=slot.match(/(\d{1,2}):(\d{2})\s(AM|PM)/);if(!match)return "10:15 AM";let hour=Number(match[1])%12;if(match[3]==="PM")hour+=12;let minutes=(hour*60)+Number(match[2])-25;if(minutes<0)minutes+=1440;const displayHour=(Math.floor(minutes/60)%12)||12;const displayMinute=String(minutes%60).padStart(2,"0");const period=minutes>=720?"PM":"AM";return `${displayHour}:${displayMinute} ${period}`}
function AppointmentCompanionSheet({close}:{close:()=>void}){return <div className="sheet-overlay"><section className="bottom-sheet companion-sheet"><button className="sheet-close" onClick={close}>×</button><span className="sheet-handle"/><h2>Appointment companion</h2><p>Everything you need for a smooth visit.</p><SheetList title="Document guide" items={["Existing passport + self-attested copies","Original proof of present address","Original proof of date of birth","Affidavit and supporting records, if applicable"]}/><SheetList title="Facilities at the centre" items={["Accessible entrance","Token help desk","Seating area and drinking water","Parking nearby"]}/><div className="companion-actions"><button>Reschedule appointment</button><button>Cancel appointment</button><button>FAQs about your visit　›</button></div></section></div>}
function SheetList({title,items}:{title:string;items:string[]}){return <section className="sheet-list"><h3>{title}</h3><ul>{items.map(item=><li key={item}>✓　{item}</li>)}</ul></section>}

function Companion({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label">YOUR APPOINTMENT</p><h2>We&apos;ll help you arrive prepared</h2><div className="arrival-card"><b>Report by 10:15 AM</b><p>Passport Seva Kendra, Bengaluru<br/>Token BNC-048 · Appointment 10:40 AM</p></div><h3>Bring these originals</h3><ul className="bring-list"><li>Existing passport + self-attested copies</li><li>Original proof of present address</li><li>Original proof of date of birth</li><li>All change / affidavit supporting records</li></ul><div className="facilities"><b>At the centre</b><span>♿ Accessible entrance　☕ Refreshments　⌖ Parking nearby</span></div><button className="flow-cta" onClick={()=>go("live")}>I&apos;ve arrived at the centre　→</button><button className="text-action">Reschedule / cancel appointment</button></section>}
function LiveVisit({go}:{go:(p:Screen)=>void}){return <section className="flow-screen"><p className="step-label live-label">● APPOINTMENT IN PROGRESS</p><h2>Report directly to Counter C</h2><p>Your earlier completed steps are preserved. You don&apos;t need to restart at Counter A.</p><div className="queue-status"><span>●</span><div><small>LIVE QUEUE</small><b>You&apos;re next in 12 minutes</b></div></div><div className="timeline"><Time done title="Token verified" text="10:17 AM"/><Time done title="Document pre-check complete" text="Resumed from earlier visit"/><Time active title="Counter C · Biometrics" text="Proceed when called"/><Time title="Granting decision" text="After biometrics"/></div><button className="flow-cta" onClick={()=>go("tracking")}>Complete submission demo　→</button></section>}
function Time({title,text,done,active}:{title:string;text:string;done?:boolean;active?:boolean}){return <div className="time"><span className={done?"done":active?"active":""}>{done?"✓":active?"3":"4"}</span><div><b>{title}</b><small>{text}</small></div></div>}
function Tracking({go,center,slot,appointmentRescheduled,applicationSubmitted}:{go:(p:Screen)=>void;center:PassportCenter;slot:PassportCenter["slots"][number];appointmentRescheduled:boolean;applicationSubmitted:boolean}) {
  const appointmentLabel=appointmentRescheduled?"Thu, 05 Sep · 09:30 AM":slot.label;
  return <section className="flow-screen tracking-screen"><p className="step-label">PASSPORT TRACKING</p><h2>{applicationSubmitted?"Application submitted":"Application in progress"}</h2><p>{applicationSubmitted?"Your application was submitted successfully at the PSK. Police verification is now in progress.":"This is the single source of truth for your passport reissue and every appointment update."}</p>
    <article className={`application-progress-card ${applicationSubmitted?"submitted":""}`}><div className="progress-card-head"><span>{applicationSubmitted?"✓":"↻"}</span><div><small>APPLICATION NUMBER</small><b>BN1064822518426</b></div><em>{applicationSubmitted?"SUBMITTED":"IN PROGRESS"}</em></div><div className="appointment-truth"><small>{applicationSubmitted?"CURRENT STATUS":appointmentRescheduled?"APPOINTMENT RESCHEDULED":"APPOINTMENT SCHEDULED"}</small><b>{applicationSubmitted?"Police verification in progress":appointmentLabel}</b><p>{applicationSubmitted?"An officer has been assigned for your address verification.":`${center.name} · Report by ${reportingTime(appointmentLabel)}`}</p></div>{!applicationSubmitted&&<button onClick={()=>go("book")}>View appointment details　›</button>}</article>
    <h3>Application progress</h3><div className="timeline">{applicationSubmitted?<><Time done title="Application submitted at PSK" text="Your passport reissue application has been accepted"/><Time done title="Document review complete" text="All required records were verified"/><Time done title="Appointment completed" text={`${appointmentLabel} · ${center.area}`}/><Time active title="Police verification" text="Officer assigned · home verification scheduled"/><section className="assigned-officer-card"><div className="officer-card-label"><span>●</span> OFFICER ASSIGNED <em>VERIFICATION SCHEDULED</em></div><div className="officer-profile"><span className="officer-avatar">KS</span><div><b>Sub-Inspector Kavya Sharma</b><small>Indiranagar Police Station · Bengaluru East</small></div><i>✓</i></div><div className="officer-details"><div><small>HOME VISIT WINDOW</small><b>Fri, 06 Sep · 10:00 AM–1:00 PM</b></div><div><small>CONTACT</small><b>Official number ending 4812</b></div></div><p>Keep your original address proof ready. No payment is required for police verification.</p></section><Time title="Printing and dispatch" text="Delivery tracking will appear after verification"/></>:<><Time done title="Application submitted" text="Your reissue application is saved in UMANG"/><Time done title="Document review complete" text="Required documents are ready"/><Time active title={appointmentRescheduled?"Return appointment rescheduled":"Passport Seva appointment"} text={`${appointmentLabel} · ${center.area}`}/><Time title="Application submission at PSK" text="Updates after your physical visit will appear here"/><Time title="Police verification" text="Officer and visit information will appear after submission"/><Time title="Printing and dispatch" text="Delivery tracking will appear here"/></>}</div><button className="flow-cta" onClick={()=>go("dashboard")}>Back to Passport Seva　→</button></section>
}
